### ISSUE TITLE
flarum-auth-twitter not working

### ISSUE THREAD

**Issue by rikusen0335** [Littlegolden/flarum-lang-japanese#2]
This translation isn't worked, idk the reason because the yaml is correct.
In v0.1.0-beta.**12** worked, but in v0.1.0-beta.**13** doesn't work.
![SnapCrab_NoName_2020-6-8_13-20-50_No-00](https://user-images.githubusercontent.com/19174234/83993335-16220580-a98e-11ea-8b87-68dd5330d5b6.png)

**Comment by littlegolden** [comment]
I'm sorry it's been a busy time and I didn't get back to you in time.

Since beta13, Flarum will only read translations of plugns that enabled. Therefore, after opening a new plugin, users may need to restart the language pack in order for flarum to load the translations.

I have invited you to co-manage this repository, initially this Japanese package was made for the csur forum, so some of the translations are not correct, it will be great if you are interested in this.

**Comment by rikusen0335** [comment]
I see, and so enabling twitter auth and re-activate laguage pack works fine! Thanks.

And I appreciate the invitation. I'd like to fixing up them!

**Comment by rikusen0335** [comment]
Though this issue is not an issue so I'm closing this, and I have to write them in Japanese too!

日本語の解決方法:
Flarumはbeta13から、言語パックが有効化されている際に有効化されているプラグインの翻訳のみを読み込むようになりました。なので、新しいプラグインを追加するときは、その新しいプラグインを有効化して、そのあとに言語パックを再有効化(無効化してから→有効化)してください。これが助けになれば幸いです。
